(() => {
  const CONFIG = {
    levels: [{ bpm: 60, duration: 30000 }, { bpm: 78, duration: 30000 }, { bpm: 96, duration: 30000 }, { bpm: 112, duration: 30000 }, { bpm: 126, duration: 45000 }, { bpm: 140, duration: 45000 }, { bpm: 154, duration: 45000 }, { bpm: 168, duration: 45000 }, { bpm: 182, duration: 60000 }, { bpm: 190, duration: 120000 }],
    perfect: 100,
    desktopGoodByLevel: [350, 350, 350, 300, 300, 300, 250, 250, 225, 225],
    mobileGoodByLevel: [400, 400, 400, 350, 350, 350, 300, 300, 250, 250],
    approach: 620, countInBeats: 3, spiderHitSize: { desktop: 80, mobile: 96 }, bonusUnlockHits: 3, webMax: 5, webRebuildMs: 1700, webClearDelay: 1100, rackWebLimit: 12,
    hatPoints: { perfect: 100, good: 60 }, webPoints: 5, maxDebugEvents: 8,
    physics: { spring: 17, damping: 4.2, maxVelocity: 140, stableLean: 6, dangerLean: 18, instabilityDecay: 9, highInstabilityDecay: 6.4, fallThreshold: 80, tapWindow: 900, rapidTapStart: 4, impulses: { perfect: 12, good: 38, bonus: 42, near: 65, empty: 95, duplicate: 4, emptyWeb: 8 }, gains: { perfect: 0, good: .2, bonus: 1.1, near: 5, empty: 8, duplicate: 0, emptyWeb: .4 } },
    routePlan: ['cross', 'vertical', 'diagonal', 'short', 'long', 'cross', 'vertical', 'diagonal'],
    movementPlan: ['jump', 'jump', 'scurry', 'jump', 'scurry-jump', 'scurry'],
  };
  const els = {
    score: document.querySelector('#score'), combo: document.querySelector('#combo'), level: document.querySelector('#level'), rackWebs: document.querySelector('#rackWebs'), time: document.querySelector('#time'), timeFill: document.querySelector('#timeFill'),
    stage: document.querySelector('.stage'), countIn: document.querySelector('#countIn'), spider: document.querySelector('#spider'), ring: document.querySelector('#landingRing'), trail: document.querySelector('#webTrail'), cover: document.querySelector('#webCover'), rack: document.querySelector('#rack'), message: document.querySelector('#gameMessage'), feedback: document.querySelector('#feedbackLayer'), debugPanel: document.querySelector('#debugPanel'), debugHitArea: document.querySelector('#debugHitArea'), faceHug: document.querySelector('#faceHug'),
    start: document.querySelector('#startButton'), pause: document.querySelector('#pauseButton'), restart: document.querySelector('#restartButton'), sound: document.querySelector('#soundButton'), hats: [...document.querySelectorAll('.hat')], webs: [...document.querySelectorAll('.web')], stations: [...document.querySelectorAll('.hat-station')],
  };
  const DEBUG = new URLSearchParams(window.location.search).get('debug') === '1';
  const spots = [{ x: 17.5, y: 14.1 }, { x: 82.5, y: 30.3 }, { x: 17.5, y: 46.4 }, { x: 82.5, y: 62.5 }, { x: 17.5, y: 78.6 }, { x: 82.5, y: 94.8 }];
  const mobileSpots = [{ x: 17.5, y: 10.8 }, { x: 82.5, y: 27.1 }, { x: 17.5, y: 43.4 }, { x: 82.5, y: 59.7 }, { x: 17.5, y: 76.1 }, { x: 82.5, y: 92.4 }];
  let state, audio;
  const resetState = () => ({ running: false, paused: false, sound: true, score: 0, combo: 0, spiderHits: 0, bonusUnlocked: false, levelIndex: 0, activeCount: 3, startedAt: 0, pausedAt: 0, pauseTotal: 0, target: 1, routeStep: 0, pairHistory: [], raf: 0, nextArrivalId: 1, scheduled: null, arrivals: [], trails: [], web: Array(6).fill(0), lastWebAt: Array(6).fill(0), webEmptyUntil: Array(6).fill(0), timers: new Set(), physics: { angle: 0, velocity: 0, instability: 0, lastClock: 0, taps: [], falling: false }, failure: false, debug: { pointers: 0, hits: 0, offTarget: 0, duplicates: 0, latestOffset: null, pointerType: '—', tap: '—', bounds: '—', log: [] } });
  const clockNow = () => performance.now();
  const totalDuration = () => CONFIG.levels.reduce((sum, level) => sum + level.duration, 0);
  const levelAtElapsed = elapsed => { let remaining = elapsed; for (let index = 0; index < CONFIG.levels.length; index++) { if (remaining < CONFIG.levels[index].duration) return index; remaining -= CONFIG.levels[index].duration; } return CONFIG.levels.length - 1; };
  const formatTime = ms => { const seconds = Math.max(0, Math.ceil(ms / 1000)); return `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, '0')}`; };
  const isMobileInput = pointerType => pointerType === 'touch' || (pointerType === 'pen' && window.matchMedia('(max-width: 650px)').matches);
  const activeSpots = () => window.matchMedia('(max-width: 650px)').matches ? mobileSpots : spots;
  const goodWindow = (levelIndex, pointerType = 'mouse') => { const windows = isMobileInput(pointerType) ? CONFIG.mobileGoodByLevel : CONFIG.desktopGoodByLevel; return windows[Math.min(windows.length - 1, levelIndex)]; };
  const maxGoodWindow = levelIndex => Math.max(goodWindow(levelIndex, 'mouse'), goodWindow(levelIndex, 'touch'));
  const activeHatCount = levelIndex => levelIndex >= 9 ? 6 : levelIndex >= 5 ? 5 : levelIndex >= 2 ? 4 : 3;
  const levelStateAt = elapsed => { let remaining = elapsed; for (let index = 0; index < CONFIG.levels.length; index++) { if (remaining < CONFIG.levels[index].duration) return { index, elapsed: remaining }; remaining -= CONFIG.levels[index].duration; } return { index: 9, elapsed: CONFIG.levels[9].duration }; };
  function later(fn, delay) { const id = window.setTimeout(() => { state.timers.delete(id); fn(); }, delay); state.timers.add(id); return id; }
  function clearTransientUI() { state.timers.forEach(window.clearTimeout); state.timers.clear(); els.feedback.replaceChildren(); els.hats.forEach(hat => hat.classList.remove('falling', 'replacing')); }
  const tone = (frequency, duration, type = 'sine', volume = .05) => { if (!state.sound) return; try { const Engine = window.AudioContext || window.webkitAudioContext; if (!Engine) return; if (!audio) audio = new Engine(); if (audio.state === 'suspended') audio.resume(); const oscillator = audio.createOscillator(), gain = audio.createGain(); oscillator.type = type; oscillator.frequency.value = frequency; gain.gain.setValueAtTime(volume, audio.currentTime); gain.gain.exponentialRampToValueAtTime(.001, audio.currentTime + duration); oscillator.connect(gain).connect(audio.destination); oscillator.start(); oscillator.stop(audio.currentTime + duration); } catch (_) {} };
  function updateStats() { const safeLevelIndex = Number.isInteger(state.levelIndex) ? Math.max(0, Math.min(CONFIG.levels.length - 1, state.levelIndex)) : 0, level = CONFIG.levels[safeLevelIndex]; state.levelIndex = safeLevelIndex; els.score.textContent = String(state.score).padStart(5, '0'); els.combo.textContent = `×${state.combo}`; els.level.innerHTML = `${safeLevelIndex + 1} <em>• ${level.bpm} BPM</em>`; els.rackWebs.textContent = `${state.trails.length} / ${CONFIG.rackWebLimit}`; }
  function renderDebug() { if (!DEBUG) return; const d = state.debug; els.debugPanel.hidden = false; els.debugPanel.innerHTML = `<b>INPUT DEBUG</b><br>events ${d.pointers} · hits ${d.hits} · off ${d.offTarget} · duplicate ${d.duplicates}<br>offset ${d.latestOffset ?? '—'} ms · arrival ${state.scheduled?.id ?? '—'} · ${d.pointerType}<br>tap ${d.tap}<br>hit ${d.bounds}<hr>${d.log.map(entry => `<div>${entry}</div>`).join('')}`; }
  function debugEvent(label, details = '') { if (!DEBUG) return; state.debug.log.unshift(`${Math.round(clockNow())}: ${label}${details ? ` · ${details}` : ''}`); state.debug.log.length = Math.min(state.debug.log.length, CONFIG.maxDebugEvents); renderDebug(); }
  function spiderHitBounds() { const spider = els.spider.getBoundingClientRect(), compact = window.matchMedia('(max-width: 650px)').matches, minimum = compact ? CONFIG.spiderHitSize.mobile : CONFIG.spiderHitSize.desktop, side = Math.max(minimum, spider.width, spider.height); return { left: spider.left + spider.width / 2 - side / 2, top: spider.top + spider.height / 2 - side / 2, width: side, height: side }; }
  function updateDebugHitArea() { if (!DEBUG) return; const hit = spiderHitBounds(), stage = els.stage.getBoundingClientRect(); Object.assign(els.debugHitArea.style, { left: `${hit.left - stage.left}px`, top: `${hit.top - stage.top}px`, width: `${hit.width}px`, height: `${hit.height}px` }); state.debug.bounds = `${Math.round(hit.left)},${Math.round(hit.top)} ${Math.round(hit.width)}×${Math.round(hit.height)}`; }
  function setPoint(element, point, moving) { element.style.setProperty('--x', `${point.x}%`); element.style.setProperty('--y', `${point.y}%`); element.style.setProperty('--move-time', `${moving ? CONFIG.approach : 0}ms`); }
  function setSpider(index, moving) { const spot = activeSpots()[index]; setPoint(els.spider, spot, moving); setPoint(els.ring, spot, moving); requestAnimationFrame(updateDebugHitArea); }
  function setSpiderPoint(point) { setPoint(els.spider, point, false); requestAnimationFrame(updateDebugHitArea); }
  function movementMode() { const level = state.levelIndex; if (level < 2) return 'jump'; if (level < 4) return state.routeStep % 3 === 0 ? 'scurry' : 'jump'; if (level < 6) return CONFIG.movementPlan[state.routeStep % CONFIG.movementPlan.length]; return CONFIG.movementPlan[(state.routeStep * 2 + state.levelIndex) % CONFIG.movementPlan.length]; }
  function scurryPoints(arrival) { const positions = activeSpots(), from = positions[arrival.from], to = positions[arrival.target], junctionFrom = { x: 50, y: from.y }, junctionTo = { x: 50, y: to.y }; return [from, junctionFrom, junctionTo, to]; }
  function updateScurry(arrival, clock) { const points = scurryPoints(arrival), progress = Math.max(0, Math.min(1, (clock - arrival.announceAt) / Math.max(1, arrival.arrivalAt - arrival.announceAt))), scaled = progress * (points.length - 1), segment = Math.min(points.length - 2, Math.floor(scaled)), local = scaled - segment, a = points[segment], b = points[segment + 1]; setSpiderPoint({ x: a.x + (b.x - a.x) * local, y: a.y + (b.y - a.y) * local }); }
  function drawTrail() { const positions = activeSpots(); els.trail.innerHTML = state.trails.map(({ from, to }) => { const a = positions[from], b = positions[to], mx = (a.x + b.x) * 5, my = (a.y + b.y) * 5 - 70; return `<path d="M ${a.x * 10} ${a.y * 10} Q ${mx} ${my} ${b.x * 10} ${b.y * 10}"/>`; }).join(''); }

  function renderRackPhysics() { els.rack.style.setProperty('--rack-angle', String(state.physics.angle.toFixed(3)) + 'deg'); els.rack.classList.toggle('unstable', state.physics.instability >= 55); els.rack.classList.toggle('critical', state.physics.instability >= 78); }
  function calmRack(amount) { state.physics.instability = Math.max(0, state.physics.instability - amount); state.physics.velocity *= .52; }
  function rackImpact(kind, event) { if (!state.running || state.physics.falling) return; const p = state.physics, stage = els.stage.getBoundingClientRect(), clock = clockNow(), position = (event.clientX - (stage.left + stage.width / 2)) / Math.max(1, stage.width / 2), side = Math.abs(position) < .14 ? (p.velocity >= 0 ? 1 : -1) : Math.sign(position); p.taps.push({ clock, side, kind }); p.taps = p.taps.filter(tap => clock - tap.clock <= CONFIG.physics.tapWindow); const disruptive = !['perfect', 'good', 'bonus', 'duplicate'].includes(kind), rapid = Math.max(0, p.taps.length - CONFIG.physics.rapidTapStart), alternations = p.taps.slice(1).reduce((count, tap, index) => count + (tap.side !== p.taps[index].side ? 1 : 0), 0), pressure = event.pressure > .05 && event.pressure < .95 ? 1 + (event.pressure - .5) * .16 : 1, chaos = disruptive ? rapid * .28 + alternations * .16 : Math.max(0, rapid - 2) * .05; p.velocity = Math.max(-CONFIG.physics.maxVelocity, Math.min(CONFIG.physics.maxVelocity, p.velocity + side * (CONFIG.physics.impulses[kind] + chaos) * pressure)); p.instability = Math.max(0, Math.min(130, p.instability + CONFIG.physics.gains[kind] + (disruptive ? rapid * .9 + alternations * .7 : 0))); if (kind === 'perfect') calmRack(2.4); else if (kind === 'good') calmRack(1.25); }
  function stepRackPhysics(clock) { const p = state.physics, seconds = Math.min(.05, Math.max(0, (clock - (p.lastClock || clock)) / 1000)); p.lastClock = clock; if (!seconds || p.falling) return; const decay = p.instability >= 55 ? CONFIG.physics.highInstabilityDecay : CONFIG.physics.instabilityDecay; p.instability = Math.max(0, p.instability - decay * seconds); const maxLean = CONFIG.physics.stableLean + Math.min(CONFIG.physics.dangerLean - CONFIG.physics.stableLean, p.instability * .12); p.velocity += -p.angle * CONFIG.physics.spring * seconds; p.velocity *= Math.exp(-CONFIG.physics.damping * seconds); p.velocity = Math.max(-CONFIG.physics.maxVelocity, Math.min(CONFIG.physics.maxVelocity, p.velocity)); p.angle = Math.max(-maxLean, Math.min(maxLean, p.angle + p.velocity * seconds)); renderRackPhysics(); if (p.instability >= CONFIG.physics.fallThreshold) gameOver('instability'); }
  function leaveTrail(from, to) { state.trails.push({ from, to }); drawTrail(); updateStats(); if (state.trails.length >= CONFIG.rackWebLimit) gameOver('strand'); }
  function flashRackClear(all = false) { const spider = els.spider.getBoundingClientRect(); els.rack.classList.remove('strand-cleared', 'rack-cleared'); void els.rack.offsetWidth; els.rack.classList.add(all ? 'rack-cleared' : 'strand-cleared'); later(() => els.rack.classList.remove('strand-cleared', 'rack-cleared'), all ? 520 : 290); showFeedback(all ? 'Rack cleared!' : 'Strand cut', spider.left + spider.width / 2, spider.top + spider.height / 2, all ? 'rack-clear' : 'strand-clear'); }
  function clearTrail(celebrate = false) { const hadStrands = state.trails.length > 0; state.trails = []; els.cover.innerHTML = ''; drawTrail(); updateStats(); if (celebrate && hadStrands) { calmRack(12); flashRackClear(true); } }
  function clearConnection(from, to, celebrate = true) { const before = state.trails.length; state.trails = state.trails.filter(strand => !((strand.from === from && strand.to === to) || (strand.from === to && strand.to === from))); drawTrail(); updateStats(); if (celebrate && state.trails.length < before) flashRackClear(); }
  function setActiveHatCount() { const count = activeHatCount(state.levelIndex); if (count === state.activeCount) return; state.activeCount = count; state.pairHistory = []; state.routeStep = 0; els.stations.forEach((station, index) => { const unlocked = index < count; station.classList.toggle('locked', !unlocked); els.hats[index].disabled = !unlocked; if (unlocked) station.classList.add('unlocked'); }); tone(740, .32, 'triangle', .07); const stage = els.stage.getBoundingClientRect(); showFeedback('Hat ' + count + ' joins!', stage.left + stage.width / 2, stage.top + 45, 'bonus'); }
  function routeMatches(style, from, to) {
    const a = spots[from], b = spots[to], crossRack = (a.x < 50) !== (b.x < 50), verticalDistance = Math.abs(a.y - b.y) / 100, distance = Math.hypot((a.x - b.x) / 100, verticalDistance);
    if (style === 'vertical') return !crossRack;
    if (style === 'cross') return crossRack;
    if (style === 'diagonal') return crossRack && verticalDistance >= .14;
    if (style === 'short') return distance <= .4;
    return verticalDistance >= .45 || distance >= .75;
  }
  function nextTarget() {
    const from = state.target;
    const candidates = Array.from({ length: state.activeCount }, (_, index) => index).filter(index => index !== from);
    const recent = state.pairHistory.slice(-3);
    const previouslyUsedFromHere = target => state.pairHistory.some(pair => pair.from === from && pair.to === target);
    let pool = candidates.filter(target => !previouslyUsedFromHere(target));
    if (!pool.length) pool = candidates.filter(target => !recent.some(pair => pair.from === from && pair.to === target));
    const backtrack = state.pairHistory.at(-1)?.from;
    const withoutBacktrack = pool.filter(target => target !== backtrack);
    if (withoutBacktrack.length) pool = withoutBacktrack;
    const style = CONFIG.routePlan[state.routeStep++ % CONFIG.routePlan.length];
    const styledPool = pool.filter(target => routeMatches(style, from, target));
    if (styledPool.length) pool = styledPool;
    const target = pool[(state.routeStep + from * 2) % pool.length];
    state.pairHistory.push({ from, to: target });
    const historyLimit = Math.max(18, state.activeCount * state.activeCount * 2);
    if (state.pairHistory.length > historyLimit) state.pairHistory.splice(0, state.pairHistory.length - historyLimit);
    return target;
  }
  function scheduleNextArrival(clock, isFirst = false) { const beat = 60000 / CONFIG.levels[state.levelIndex].bpm, target = nextTarget(), arrivalAt = isFirst ? state.startedAt + beat * CONFIG.countInBeats : clock + beat, levelIndex = state.levelIndex, mode = movementMode(); state.scheduled = { id: state.nextArrivalId++, from: state.target, target, mode, arrivalAt, announceAt: arrivalAt - Math.min(CONFIG.approach, beat * .78), levelIndex, maxGoodWindow: maxGoodWindow(levelIndex), announced: false, landed: false, scored: false, missed: false }; state.target = target; state.arrivals.push(state.scheduled); }
  function announceArrival(arrival) { if (arrival.announced || !state.running) return; arrival.announced = true; const approach = arrival.arrivalAt - arrival.announceAt, hat = els.hats[arrival.target], scurries = arrival.mode !== 'jump'; els.hats.forEach(h => h.classList.remove('queued', 'landed')); hat.style.setProperty('--approach', `${approach}ms`); hat.classList.add('queued'); setPoint(els.ring, activeSpots()[arrival.target], false); els.ring.style.setProperty('--approach', `${approach}ms`); els.ring.classList.add('active'); els.spider.classList.toggle('scurrying', scurries); els.spider.classList.toggle('scurry-jump', arrival.mode === 'scurry-jump'); leaveTrail(arrival.from, arrival.target); if (!state.running) return; if (scurries) updateScurry(arrival, clockNow()); else requestAnimationFrame(() => setSpider(arrival.target, true)); }
  function landArrival(arrival, clock) { if (arrival.landed) return; arrival.landed = true; setSpider(arrival.target, false); els.spider.classList.remove('scurrying', 'scurry-jump'); els.ring.classList.remove('active'); els.spider.classList.add('settled'); els.hats[arrival.target].classList.remove('queued'); els.hats[arrival.target].classList.add('landed'); later(() => els.spider.classList.remove('settled'), 240); if (state.scheduled === arrival) scheduleNextArrival(clock); }
  function markExpiredArrivals(clock) { state.arrivals.forEach(arrival => { if (!arrival.scored && !arrival.missed && clock > arrival.arrivalAt + arrival.maxGoodWindow) { arrival.missed = true; state.combo = 0; tone(130, .12, 'sawtooth', .035); debugEvent('miss', `#${arrival.id}`); } }); state.arrivals = state.arrivals.filter(arrival => clock <= arrival.arrivalAt + arrival.maxGoodWindow + 450 || (!arrival.scored && !arrival.missed)); }
  function eligibleArrival(clock, pointerType) { return state.arrivals.filter(arrival => !arrival.scored && !arrival.missed && Math.abs(clock - arrival.arrivalAt) <= goodWindow(arrival.levelIndex, pointerType)).sort((a, b) => Math.abs(clock - a.arrivalAt) - Math.abs(clock - b.arrivalAt))[0]; }
  function nearestArrival(clock) { return [...state.arrivals].sort((a, b) => Math.abs(clock - a.arrivalAt) - Math.abs(clock - b.arrivalAt))[0]; }
  function showFeedback(label, clientX, clientY, kind = 'miss') { const stage = els.stage.getBoundingClientRect(), feedback = document.createElement('span'); feedback.className = `tap-feedback ${kind}`; feedback.textContent = label; feedback.style.left = `${clientX - stage.left}px`; feedback.style.top = `${clientY - stage.top - 24}px`; els.feedback.append(feedback); later(() => feedback.remove(), 620); }
  function markTap(clientX, clientY) { if (!DEBUG) return; const stage = els.stage.getBoundingClientRect(), mark = document.createElement('i'); mark.className = 'debug-tap'; mark.style.left = `${clientX - stage.left}px`; mark.style.top = `${clientY - stage.top}px`; els.feedback.append(mark); later(() => mark.remove(), 700); }
  function resetComboWithFeedback(label, event, offset = null, impact = 'near') { state.combo = 0; rackImpact(impact, event); state.debug.latestOffset = offset === null ? null : Math.round(offset); updateStats(); tone(115, .09, 'square', .025); showFeedback(label, event.clientX, event.clientY, 'miss'); debugEvent(label.toLowerCase(), offset === null ? '' : `${Math.round(offset)}ms`); }
  function scoreArrival(arrival, clock, event) { if (arrival.scored) { state.debug.duplicates++; rackImpact('duplicate', event); showFeedback('Already hit', event.clientX, event.clientY, 'duplicate'); debugEvent('already hit', `#${arrival.id}`); return; } const offset = clock - arrival.arrivalAt, absoluteOffset = Math.abs(offset); if (absoluteOffset > goodWindow(arrival.levelIndex, event.pointerType)) return; arrival.scored = true; const perfect = absoluteOffset <= CONFIG.perfect, clearsRack = (state.combo + 1) % 3 === 0; state.score += CONFIG.hatPoints[perfect ? 'perfect' : 'good'] + Math.max(0, state.combo - 1) * 5; state.combo++; state.spiderHits++; state.debug.hits++; state.debug.latestOffset = Math.round(offset); rackImpact(perfect ? 'perfect' : 'good', event); clearConnection(arrival.from, arrival.target, !clearsRack); if (clearsRack) clearTrail(true); if (!state.bonusUnlocked && state.spiderHits >= CONFIG.bonusUnlockHits) { state.bonusUnlocked = true; els.stage.classList.add('bonus-live'); showFeedback('Bonus webs ready!', event.clientX, event.clientY, 'bonus'); } els.hats[arrival.target].classList.remove('queued'); els.hats[arrival.target].classList.add('falling'); later(() => { els.hats[arrival.target].classList.remove('falling'); els.hats[arrival.target].classList.add('replacing'); later(() => els.hats[arrival.target].classList.remove('replacing'), 550); }, 560); tone(perfect ? 740 : 530, .14, 'triangle', .06); updateStats(); showFeedback(perfect ? 'Perfect' : 'Good', event.clientX, event.clientY, perfect ? 'perfect' : 'good'); debugEvent(perfect ? 'perfect' : 'good', `#${arrival.id} ${Math.round(offset)}ms`); }
  function handleSpiderTap(event) { const clock = clockNow(), pointerType = event.pointerType || 'mouse', hit = spiderHitBounds(), inside = event.clientX >= hit.left && event.clientX <= hit.left + hit.width && event.clientY >= hit.top && event.clientY <= hit.top + hit.height; state.debug.pointers++; state.debug.pointerType = pointerType; state.debug.tap = `${Math.round(event.clientX)},${Math.round(event.clientY)}`; updateDebugHitArea(); markTap(event.clientX, event.clientY); if (!inside) { state.debug.offTarget++; resetComboWithFeedback('Off target', event, null, 'empty'); renderDebug(); return; } const eligible = eligibleArrival(clock, pointerType); if (eligible) { scoreArrival(eligible, clock, event); renderDebug(); return; } const nearest = nearestArrival(clock), windowSize = nearest ? goodWindow(nearest.levelIndex, pointerType) : goodWindow(state.levelIndex, pointerType); if (nearest?.scored && clock <= nearest.arrivalAt + windowSize) { state.debug.duplicates++; showFeedback('Already hit', event.clientX, event.clientY, 'duplicate'); debugEvent('already hit', `#${nearest.id}`); renderDebug(); return; } const offset = nearest ? clock - nearest.arrivalAt : null; resetComboWithFeedback(offset !== null && offset < -windowSize ? 'Early' : 'Late', event, offset, 'near'); renderDebug(); }
  function tearWeb(index, event, cleared) { const stage = els.stage.getBoundingClientRect(); for (let piece = 0; piece < 6; piece++) { const fragment = document.createElement('i'), angle = piece * 60 + 15, distance = 11 + (piece % 3) * 7; fragment.className = 'web-shred'; fragment.style.left = `${event.clientX - stage.left}px`; fragment.style.top = `${event.clientY - stage.top}px`; fragment.style.setProperty('--dx', `${Math.cos(angle * Math.PI / 180) * distance}px`); fragment.style.setProperty('--dy', `${Math.sin(angle * Math.PI / 180) * distance}px`); els.feedback.append(fragment); later(() => fragment.remove(), 440); } els.webs[index].classList.add(cleared ? 'cleared' : 'torn'); later(() => els.webs[index].classList.remove('torn'), 250); }
  function tapWeb(index, event) { if (!state.running || state.paused || !state.bonusUnlocked || index >= state.activeCount || state.web[index] < 1) { if (state.running) rackImpact('emptyWeb', event); return; } state.web[index]--; state.score += CONFIG.webPoints; const cleared = state.web[index] === 0; if (cleared) { state.webEmptyUntil[index] = clockNow() + CONFIG.webClearDelay; state.lastWebAt[index] = clockNow(); } rackImpact('bonus', event); tearWeb(index, event, cleared); tone(880, .035, 'triangle', .025); updateStats(); renderWeb(index); showFeedback(cleared ? `Cleared! +${CONFIG.webPoints}` : `+${CONFIG.webPoints}`, event.clientX, event.clientY, 'bonus'); }
  function renderWeb(index) { const amount = state.web[index], web = els.webs[index]; web.classList.toggle('ready', state.bonusUnlocked && amount > 0); web.classList.toggle('cleared', state.bonusUnlocked && amount === 0); web.style.setProperty('--web-strength', String(.2 + .8 * amount / CONFIG.webMax)); web.querySelector('small').textContent = state.bonusUnlocked ? `+${CONFIG.webPoints} · ${amount}/${CONFIG.webMax}` : 'UNLOCK AT 3 HITS'; }
  function rebuildWebs(clock) { state.web.forEach((amount, index) => { if (state.bonusUnlocked && index < state.activeCount && clock >= state.webEmptyUntil[index] && amount < CONFIG.webMax && clock - state.lastWebAt[index] >= CONFIG.webRebuildMs) { state.web[index]++; state.lastWebAt[index] = clock; renderWeb(index); } }); }
  function revealGameOver(cause) { els.message.classList.remove('hidden'); els.message.querySelector('p').innerHTML = cause === 'instability' ? 'Rack lost its balance!<br><small>Too much frantic tapping sent it over.</small>' : 'Rack tipped over!<br><small>Too many silk strands covered the rack.</small>'; els.start.innerHTML = 'Try again <span>↻</span>'; }
  function gameOver(cause = 'strand') { if (!state.running || state.failure) return; state.running = false; state.failure = true; state.physics.falling = true; cancelAnimationFrame(state.raf); els.pause.disabled = true; els.ring.classList.remove('active'); els.spider.classList.remove('scurrying', 'scurry-jump'); els.rack.classList.add('tipping'); tone(95, .65, 'sawtooth', .07); if (cause !== 'instability') return revealGameOver(cause); const spider = els.spider.getBoundingClientRect(); els.faceHug.style.setProperty('--hug-x', `${spider.left + spider.width / 2}px`); els.faceHug.style.setProperty('--hug-y', `${spider.top + spider.height / 2}px`); els.faceHug.classList.remove('hidden', 'launch'); els.faceHug.classList.add('prepare'); later(() => { els.faceHug.classList.add('launch'); els.stage.classList.add('face-shake'); }, 220); later(() => { els.stage.classList.remove('face-shake'); els.faceHug.className = 'face-hug hidden'; revealGameOver(cause); }, 900); }
  function finish() { state.running = false; cancelAnimationFrame(state.raf); els.pause.disabled = true; els.message.classList.remove('hidden'); els.message.querySelector('p').innerHTML = `Set complete!<br><small>${String(state.score).padStart(5, '0')} points · best combo ×${state.combo}</small>`; els.start.innerHTML = 'Play again <span>↻</span>'; tone(760, .3, 'triangle', .07); }
  function updateCountIn(clock) { if (!state.scheduled || state.scheduled.id !== 1 || state.scheduled.announced) { els.countIn.textContent = ''; return; } const beat = 60000 / CONFIG.levels[state.levelIndex].bpm, beats = Math.max(1, Math.ceil((state.scheduled.arrivalAt - clock) / beat)); els.countIn.textContent = `Get ready · ${beats}`; }
  function gameLoop(clock) { if (!state.running || state.paused) return; const elapsed = clock - state.startedAt - state.pauseTotal, progression = levelStateAt(elapsed), level = CONFIG.levels[progression.index]; if (progression.index !== state.levelIndex) { state.levelIndex = progression.index; setActiveHatCount(); updateStats(); tone(620, .3, 'triangle', .06); } els.time.textContent = formatTime(level.duration - progression.elapsed); els.timeFill.style.width = String(Math.max(0, 1 - progression.elapsed / level.duration) * 100) + '%'; stepRackPhysics(clock); updateCountIn(clock); rebuildWebs(clock); if (state.scheduled && !state.scheduled.announced && clock >= state.scheduled.announceAt) announceArrival(state.scheduled); if (state.scheduled?.announced && !state.scheduled.landed && state.scheduled.mode !== 'jump') updateScurry(state.scheduled, clock); if (state.scheduled && !state.scheduled.landed && clock >= state.scheduled.arrivalAt) landArrival(state.scheduled, clock); markExpiredArrivals(clock); updateDebugHitArea(); renderDebug(); if (!state.running) return; if (elapsed >= totalDuration()) return finish(); state.raf = requestAnimationFrame(gameLoop); }
  function start() { clearTransientUI(); cancelAnimationFrame(state?.raf); state = resetState(); state.running = true; state.startedAt = clockNow(); state.target = 1; setSpider(1, false); clearTrail(); state.physics.lastClock = state.startedAt; renderRackPhysics(); els.stage.classList.remove('bonus-live', 'face-shake'); els.countIn.textContent = ''; els.rack.classList.remove('tipping', 'unstable', 'critical'); els.faceHug.className = 'face-hug hidden'; els.stations.forEach((station, index) => { station.classList.toggle('locked', index >= 3); station.classList.remove('unlocked'); els.hats[index].disabled = index >= 3; }); els.ring.classList.remove('active'); els.message.classList.add('hidden'); els.pause.disabled = false; els.pause.innerHTML = 'Ⅱ <span>Pause</span>'; els.webs.forEach((_, index) => renderWeb(index)); updateStats(); scheduleNextArrival(state.startedAt, true); state.raf = requestAnimationFrame(gameLoop); tone(440, .12, 'triangle', .05); debugEvent('start'); }
  function togglePause() { if (!state.running) return; state.paused = !state.paused; if (state.paused) { state.pausedAt = clockNow(); cancelAnimationFrame(state.raf); clearTransientUI(); els.pause.innerHTML = '▶ <span>Resume</span>'; } else { const clock = clockNow(), pausedFor = clock - state.pausedAt; state.pauseTotal += pausedFor; state.physics.lastClock = clock; state.arrivals.forEach(arrival => { arrival.arrivalAt += pausedFor; arrival.announceAt += pausedFor; }); els.pause.innerHTML = 'Ⅱ <span>Pause</span>'; state.raf = requestAnimationFrame(gameLoop); } }
  function onStagePointerDown(event) { if (event.pointerType === 'mouse' && event.button !== 0) return; if (event.target.closest('#startButton')) return; event.preventDefault(); const web = event.target.closest('.web'); if (web) { tapWeb(els.webs.indexOf(web), event); return; } if (!state.running || state.paused) return; handleSpiderTap(event); }
  els.stage.addEventListener('pointerdown', onStagePointerDown, { passive: false });
  els.start.addEventListener('click', start); els.restart.addEventListener('click', start); els.pause.addEventListener('click', togglePause);
  els.sound.addEventListener('click', () => { state.sound = !state.sound; els.sound.innerHTML = `♫ <span>${state.sound ? 'On' : 'Off'}</span>`; if (state.sound) tone(660, .06); });
  window.addEventListener('resize', () => { drawTrail(); setSpider(state.scheduled?.announced ? state.scheduled.target : state.target, Boolean(state.scheduled?.announced && !state.scheduled?.landed)); updateDebugHitArea(); }, { passive: true });
  document.addEventListener('visibilitychange', () => { if (document.hidden && state.running && !state.paused) togglePause(); });
  state = resetState(); updateStats(); setSpider(1, false); clearTrail(); renderRackPhysics(); els.webs.forEach((_, index) => renderWeb(index)); renderDebug();
})();
